### ISSUE TITLE
Support for syntax highlighting

### ISSUE THREAD

**Issue by alehechka** [bufbuild/vscode-buf#105]
Have been enjoying using `buf` to manage proto dependencies, builds, and generation. I do have this buf extension added to VSCode, but feel it is lacking when it comes to syntax highlighting. Currently, I am also using [vscode-proto3](https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3) to add syntax highlighting to my proto files, but that extension falls short in a couple areas, but the main one being it is unable to recognize imported proto files that `buf` imports as dependencies. 

I'm sure it would be a large undertaking, but it would be amazing if this vscode extension also came packaged with syntax highlighting for `.proto` files as well as `buf.*.yaml` with support for dependency management of imports.

**Comment by dylan-bourque** [comment]
I'm in the same situation, including using `vscode-proto3` for syntax highlighting.  We have **A LOT** of .proto files, so this is an all day, every day annoyance for me.  Who do I need to bribe to get this moving?

**Comment by alee792** [comment]
https://github.com/zxh0/vscode-proto3/issues/138#issuecomment-1241216593

This snippet is an adequate workaround for me. Works like a charm!

**Comment by advanderveer** [comment]
Just re-using the syntax highlighting from vscode-proto3 can be done pretty easily since it is just defined here: https://github.com/zxh0/vscode-proto3/tree/master/syntaxes. And then just needs to be enabled in the package.json like so: https://github.com/zxh0/vscode-proto3/blob/master/package.json#L49 

The grammar has failed on me in the past through with complicated options used on protobuf service rpcs, so it's not perfect. But it is better then getting annoyed by the error messages as mentioned in this issue.

Maybe the authors of this plugin can indicate if they would be interested in such an improvement then someone (maybe me) can contribute it.

**Comment by tlyons-cs** [comment]
Following up to see if this is something the maintainers would be open to. I don't know who would have the authority to green light it, but pinging @doriable / @paul-sachs for your input

**Comment by Alfus** [comment]
Added in https://github.com/bufbuild/vscode-buf/pull/323

**Comment by dylan-bourque** [comment]
Really excited to see this!  Any guesses on an ETA for the new release?

**Comment by paul-sachs** [comment]
🚀 v0.5.3 has been released with this feature
