### ISSUE TITLE
Automatic import suggestions

### ISSUE THREAD

**Issue by laeo** [bufbuild/vscode-buf#14]
The experience of writing protobuf on VS Code is very bad, but if we can have auto import that based on buf's dependencies management, and code suggestion also based on buf, it would be very elegant. Anyway, thanks a lot.

**Comment by johanbrandhorst** [comment]
This sort of functionality is definitely on our roadmap, but it's unfortunately not a high priority right now.

**Comment by amckinney** [comment]
Thanks for the suggestion! Similar to our response in https://github.com/bufbuild/vscode-buf/issues/8#issuecomment-921147934, we plan to implement the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (LSP) for these types of features.

This implementation will likely exist in a different place that isn't VSCode-specific (the LSP implementation applies to many more editors, for example), so I'll close this issue for now since there's nothing actionable in `vscode-buf`.
