### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by yoitsro** [bufbuild/vscode-buf#8]
Hey! This is a great start! Thank you.

It'd be great if buf could provide syntax highlight, much like what this extension does https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3

**Comment by laeo** [comment]
I had copy and paste the highlight and snippets from vscode-proto3 into my forked vscode-buf repo, if you need, you can download the source code and compile it yourself.

**Comment by amckinney** [comment]
Like https://github.com/bufbuild/vscode-buf/pull/19 suggests, we won't be working on this feature in this repository. We have big plans for a larger IDE integration story, which includes implementing the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (LSP) for Protobuf (described in our [roadmap](https://docs.buf.build/roadmap#better-ide-integration)).

As of the [latest release](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#whatIsNew) (3.16), LSP actually supports syntax highlighting, so this feature will likely exist in a different place that isn't VSCode-specific (the LSP implementation applies to many more editors, for example).

I'll close this issue for now since there's nothing actionable in `vscode-buf`.
